// This file is auto-generated by @hey-api/openapi-ts

export const $MedicalDevice = {
    properties: {
        name: {
            type: 'string'
        },
        image: {
            type: 'string'
        },
        link: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    },
    type: 'object',
    required: ['description', 'image', 'link', 'name'],
    title: 'MedicalDevice'
} as const;