// This file is auto-generated by @hey-api/openapi-ts

export const $DeviceType = {
    type: 'string',
    enum: ['Pacemaker', 'ICD', 'CRT-P', 'CRT-D', 'Other'],
    title: 'DeviceType'
} as const;

export const $Manufacturer = {
    type: 'string',
    enum: ['Biotronik', 'Medtronic', 'Boston Scientific', 'Abbott', 'Other'],
    title: 'Manufacturer'
} as const;

export const $MedicalDeviceResult = {
    properties: {
        name: {
            type: 'string'
        },
        type: {
            '$ref': '#/components/schemas/DeviceType'
        },
        manufacturer: {
            '$ref': '#/components/schemas/Manufacturer'
        },
        confidence: {
            type: 'number'
        },
        link: {
            oneOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        description: {
            oneOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        image: {
            oneOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ]
        },
        leads: {
            oneOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['confidence', 'manufacturer', 'name', 'type'],
    title: 'MedicalDeviceResult'
} as const;
