// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { PostApiClassifyData, PostApiClassifyResponse, GetApiResponse } from './types.gen';

export class DefaultService {
    /**
     * ClassifyMedicalDevice
     * @param data The data for the request.
     * @param data.formData
     * @returns MedicalDeviceResult Document created, URL follows
     * @throws ApiError
     */
    public static postApiClassify(data: PostApiClassifyData): CancelablePromise<PostApiClassifyResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/classify',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                400: 'Bad request syntax or unsupported method'
            }
        });
    }
    
}

export class SystemService {
    /**
     * HealthCheck
     * @returns unknown Request fulfilled, document follows
     * @throws ApiError
     */
    public static getApi(): CancelablePromise<GetApiResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api'
        });
    }
    
}