// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { PostApiClassifyData, PostApiClassifyResponse } from './types.gen';

export class DevicesService {
    /**
     * ClassifyMedicalDevice
     * @param data The data for the request.
     * @param data.requestBody
     * @returns MedicalDevice Document created, URL follows
     * @throws ApiError
     */
    public static postApiClassify(data: PostApiClassifyData): CancelablePromise<PostApiClassifyResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/classify',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad request syntax or unsupported method'
            }
        });
    }
    
}