// This file is auto-generated by @hey-api/openapi-ts

export type MedicalDevice = {
    name: string;
    image: string;
    link: string;
    description: string;
};

export type PostApiClassifyData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type PostApiClassifyResponse = MedicalDevice;

export type GetApiResponse = {
    [key: string]: unknown;
};

export type $OpenApiTs = {
    '/api/classify': {
        post: {
            req: PostApiClassifyData;
            res: {
                /**
                 * Document created, URL follows
                 */
                201: MedicalDevice;
                /**
                 * Bad request syntax or unsupported method
                 */
                400: {
                    status_code: number;
                    detail: string;
                    extra?: {
                        [key: string]: unknown;
                    } | null;
                };
            };
        };
    };
    '/api': {
        get: {
            res: {
                /**
                 * Request fulfilled, document follows
                 */
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
};