// This file is auto-generated by @hey-api/openapi-ts

export type DeviceType = 'Pacemaker' | 'ICD' | 'CRT-P' | 'CRT-D' | 'Other';

export type Manufacturer = 'Biotronik' | 'Medtronic' | 'Boston Scientific' | 'Abbott' | 'Other';

export type MedicalDeviceResult = {
    name: string;
    type: DeviceType;
    manufacturer: Manufacturer;
    confidence: number;
    link?: string | null;
    description?: string | null;
    image?: string | null;
    leads?: number | null;
};

export type PostApiClassifyData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type PostApiClassifyResponse = Array<MedicalDeviceResult>;

export type GetApiHealthResponse = {
    [key: string]: unknown;
};

export type GetApiResponse = {
    [key: string]: unknown;
};

export type $OpenApiTs = {
    '/api/classify': {
        post: {
            req: PostApiClassifyData;
            res: {
                /**
                 * Document created, URL follows
                 */
                201: Array<MedicalDeviceResult>;
                /**
                 * Bad request syntax or unsupported method
                 */
                400: {
                    status_code: number;
                    detail: string;
                    extra?: {
                        [key: string]: unknown;
                    } | null;
                };
            };
        };
    };
    '/api/health': {
        get: {
            res: {
                /**
                 * Request fulfilled, document follows
                 */
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
};